fix the no fire sound problem
Unity-Technologies/com.unity.multiplayer.samples.bitesize pull request #126
Opened 2023-06-09 00:49 UTC by Alexander5421

try to solve #125

2023-06-09 00:49 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.bitesize?pullRequest=126) it.</sub>

2023-09-21 20:15 UTC, fernando-cortez requested changes
Looks good besides the changes I've mentioned!

2023-09-21 20:15 UTC, fernando-cortez commented on Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
> +using System.Runtime.CompilerServices;
This directive can be removed!

2023-09-21 20:15 UTC, fernando-cortez commented on Basic/2DSpaceShooter/Assets/Scripts/ShipControl.cs
> +
This extra space should be removed!

2023-09-21 20:16 UTC, fernando-cortez commented
Hi @Alexander5421, this PR looks good. However, if your PR could target our develop branch, that would be greatly appreciated.

Having the fire sound be played on the invocation of a ClientRpc is a good fix!

2023-09-23 06:16 UTC, Alexander5421 commented
Hi @fernando-cortez, I created a new pull request #138  and merged it into develop instead of the main

2023-12-11 21:21 UTC, fernando-cortez commented
@Alexander5421 
Thanks again for your contribution.
I'm closing this PR as your latest PR has been integrated into one of our staging branches [here](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize/pull/148).

2023-12-11 21:21 UTC, closed without merging